name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_HOST}}
      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            docker build --tag ${{ secrets.DOCKER_TAG }} .
            docker stop ${{ secrets.DOCKER_IMAGE }} || true
            docker rm ${{ secrets.DOCKER_IMAGE }} || true
            docker run --name ${{ secrets.DOCKER_IMAGE }} -d -p ${{ secrets.PORT }} ${{ secrets.DOCKER_TAG }}
          EOF
      - name: Clean up
        run:
         rm -rf ~/.ssh
