name: PR
on:
  pull_request:
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
          cache: true
          cache-dependency-path: go.sum
          
      - name: Setup swagger 
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=10m

      - name: Build
        run: go build -o bin/server ./cmd/init/main.go

      - name: Swagger
        run: make gen-docs
